# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  database: <%= ENV['HEROKU_DB_NAME'] %>
  username: <%= ENV['HEROKU_DB_USER'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  host: <%= ENV['HEROKU_DB_HOST'] %>

test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_prod
  pool: 5
  timeout: 5000
